// Function to dynamically add images to the grid
function createImageGrid() {
    const grid = document.querySelector('.image-grid');
    const imagePaths = ['../assets/images/safad.jpg', '../assets/images/acre.jpg', '../assets/images/tiberias.jpg', '../assets/images/haifa.jpg', '../assets/images/nazareth.jpg', '../assets/images/baysan.jpg', '../assets/images/jenin.jpg', '../assets/images/tulkarm.jpg', '../assets/images/nablus.jpg', '../assets/images/jaffa.jpg', '../assets/images/ramallah.jpeg', '../assets/images/alramla.jpg', '../assets/images/jerusalem.jpg', '../assets/images/hebron.jpg', '../assets/images/gaza.jpeg', '../assets/images/beersheba.jpg'];
    const imageTexts = [
        "Safad lies in the hills of eastern Galilee and was long the most important town in northern Galilee. Its strategic and economic value stemmed from the fact that it lay along historic trade and communications lines between Syria and Egypt. Safad's importance thus made it a prize for various armies over the centuries, including those of Crusaders, Napoleon Bonaparte, and various Islamic dynasties. War was not the only disaster to befall Safad; like other towns in Palestine, it sustained damage during earthquakes, particularly the severe earthquake of 1837. It was also the administrative center of the sub-district carrying its name, beginning in the Ottoman era in 1886 and during the period of the British PALESTINE MANDATE. Governmental presence led to the establishment of schools, beginning in 1880. Safad was a relatively large Palestinian town during the first half of the twentieth century. Its population stood at some 12,000 during World War I, although this number had dropped to 8, 761 in 1922 as a result of wartime exigencies. The population had returned to some 13,300, 20 percent of whom were Jews, by 1948. Historically, economic activity centered around trade, artisanal production (especially wool and cotton textiles), and, given its location in the hills, summer tourism. Safad's 1,429 dunums of land was largely hilly, restricting agriculture predominantly to horticulture.",
        "Arabic, Akka; Acre was one of Palestine's two major seaports (the other was JAFFA) until the twentieth century and was a fortified town of significant political import throughout Palestine's history. Lying at the foothills of Galilee on the northern end of the Gulf of Acre, the city's location has given it a vital strategic importance for both defenders and potential conquerors. Acre's current walls date from the ninth century. In 1104, Acre fell to Crusaders and became the main seaport for the Latin Kingdom of Jerusalem. After changing hands several times, the city became the last Crusader stronghold in Palestine to fall, in 1291. In 1799, it earned the distinction of resisting Napoleon's conquest of Egypt and Palestine. Acre was a major seaport and trade center for Greater Syria. The Ottoman sultan Sulayman the Lawgiver (the Magnificent) allowed the French king Francis I to station French traders in the city. In the seventeenth century, the regional ruler Fakhr al-Din II undertook many construction projects in the city , which was benefiting from the rise in European trade with the eastern Mediterranean. The Palestinians of Acre flourished during the rule of Zahir al-Umar in the third quarter of the eighteenth century , and so they undertook more rebuilding during the rule of the Ottoman governor Ahmad Jazzar Pasha. By the Ottoman era, Acre was a major port for the export of grain, which arrived from Hawran in southern Syria via camel caravan.",
        "If cities arise and struggle to survive, then the city of Tiberias has had this characteristic since its inception, like the rest of the cities of the Palestinian Valley (Semakh, Beisan, and Jericho), which together formed part of the cities of the Syrian-African collapse line in the Levant. Since the beginning of AD history, the city has had the characteristic of flexibility, adaptation and analysis in order to survive, thus responding to the circumstances that surrounded its location. The numerous sites on which the city was founded were evidence of this. The city of Tiberias is located in the northeast of Palestine. It is the center of the Tiberias District, one of the four districts that made up the Akko District during the Ottoman era and the days of the British Mandate. The city is located on the western shore of Lake Tiberias, at the basin of the eastern Galilee, twenty kilometers south of the mouth of the Jordan River in Lake Tiberias, and nine kilometers north of the river's outlet in the southwestern corner of the lake.The city of Tiberias is 160 km from Jerusalem, 141 km from Lod*, 86 km from Acre*, and 194 km from Majdal Ashkelon*. It is 71 and 137 km away from the cities of Quneitra and Damascus in Syria. It is connected to Haifa* by a main road that passes through Nazareth*, and it is also connected to Afula*, Jenin*, Nablus* and Jerusalem. There is a main road linking Tiberias to Samakh* and Beisan*, and a road branches off from it towards Afula. A main road departs from Tiberias, heading north to Metulla, and another road departs from it, heading north-west towards Safed* and Acre. In addition, there is a group of secondary roads linking the city to the neighboring villages of the district.",
        "Haifa lies along the Mediterranean Sea on the Gulf of Acre at the foot of Mount Carmel. A small fishing village in the nineteenth century, Haifa developed gradually into a major seaport in northern Palestine. The dramatic changes in its size, economy, and demography ensued as the city was trans formed by a variety of forces, including the modern global economy and ZIONISM. Haifa's origins are ancient, although the site of the present-day city dates to the late eighteenth century, when it was established by Zahir al-Umar, the strongman of northern Palestine. Haifa was ruled thereafter by Ahmad Jazzar Pasha, who governed from ACRE; was briefly conquered by Napoleon's army in 1799 before being occupied by Ibrahim Pasha's Egyptian forces, and finally came under direct Ottoman rule after 1840. Haifa contains several important religious shrines. Jews venerate the Cave of Elijah. The city also contains the tombs of two major figures in the Baha'i faith: the Bab (Mirza Ali Muhammad), buried on Mount Carmel, and Abbas Efendi, the son and successor of the faith's founder, Baha'ullah. It was during the LATE OTTOMAN PERIOD that the port began its transformation into a modern city. Aspects of this change were the growth in Haifa's population and the change in its demographic character. Haifa's population stood at some 4,000 Palestinians at the beginning of the nineteenth century. Its population began growing during the second half of that century, when its largely Muslim and Christian Palestinian demographic character likewise began to change. In 1869, German farmers from the religious Templar Society movement settled in Haifa. In the 1880s, Jews began arriving from Europe-even before the onset of political Zionism. At the same time, Haifa began to be transformed by the period's global economy and global transportation. Increasing numbers of European steamships began calling on Haifa's ports as Europe's trade with the eastern Mediterranean increased. In 1859, the Russians built a quay to facilitate such trade, and the Ottomans built the first port facilities in 1908. The Ottoman government had earlier linked Haifa with TIBERIAS by road, and by 1905, they linked it to Damascus via a spur of the Hijaz railroad. By 1919, the city was also connected to Egypt via railroad. By World War I, Haifa had replaced Beirut as the main port serving northern Palestine, southern Syria, and the tansjordanian hinterland. Grain and other commodities flowed in its direction.",
        "Nazareth is an Arab city and the district center bears its name. It is one of the largest and most beautiful cities in Palestine, and it has a special place in the hearts of Christians around the world. They make pilgrimages to it just as they make pilgrimages to the Church of the Resurrection in Jerusalem* and the Church of the Nativity in Bethlehem*. Jesus Christ was attributed to her, so he was called the Nazarene, and his followers were known as Christians at times and Christians at other times. If Safed* is the capital of the Upper Galilee, then Nazareth is the capital of the Lower Galilee. It has been the base of Nazareth District since the late Ottoman era. Nazareth has been subjected to Israeli occupation since 1948, and a small number of its residents immigrated as a result, and most of them remained steadfast despite the cruelty of the occupation and its neglect of the city’s affairs. The city remained as it was, without development, despite more than thirty years of occupation, and it declined projects, and there was a growing deficit in its municipal budget. Not only was Al-Nasser Arabiya exposed to backwardness and neglect, but it also began to suffer from suffocation and tyranny at the hands of the occupation authorities, who established the city of “Tzarit Illit,” meaning Upper Nazareth, on a mountain high near it to control the necks of its residents. Geographical location: Nazareth is located in the heart of the Lower Galilee and overlooks the Marj Ibn Amer plain* from the north. It is therefore a transitional point between the plain Marj Ibn Amer region and the mountainous Upper Galilee region. Its geographical location has been important since ancient times, as there were secondary roads connecting it to the main roads linking Syria and Egypt on the one hand, and Jordan and Palestine on the other hand. Some commercial caravans used to pass by it as they passed through the plain of Marj Ibn Amir.",
        "Bisan is an Arab city, one of the oldest cities in Palestine, that fell under Israeli occupation on May 12, 1948 (see: Bisan, Battle - 1948). If the roads* contributed to the establishment of Bisan in the beginning, then the city later became a major factor in attracting the road to it. It became connected to neighboring regions through a vital network of important roads. The paved road running along the western valley connects Beit Shean to Tiberias*, 38 km to the north. It is connected to Jerusalem* in the south by another road that passes through Jericho* with a length of 127 km. From Beit Shean comes a third paved road that runs through the plain of Marj Ibn Amer to Afula* at a distance of 27 km and extends to Haifa* at a distance of 71 km. Two roads branch out from it, one of which goes north to Nazareth* (41 km). The second goes south to Jenin* (23 km), and to Nablus* (76 km). Bisan is connected to Jordan and Syria by paved roads heading east to cross the Jordan River* at the Sheikh Hussein Bridge (7.5 km), the Damieh Bridge in the south (51 km), and the Majma` Bridge in the north (17 km). Beisan is located at the 59th kilometer of the Haifa-Daraa railway line, and with this railway line Beisan is connected to Samakh* on the southeastern shore of Lake Tiberias* (27 km) and then connected to Daraa and Damascus.",
        "The First Battle of Jenin, which took place between the second and fourth of June 1948 in the sector of the Palestinian city of Jenin and its rural depth, is considered one of the most influential battles on the course of the war in the second half of 1948. This battle has many tactical and strategic implications and many short-term and long-term repercussions on the course of the battles. And on the morale and steadfastness of the Palestinian people in this important sector of the fighting fronts. From the beginning, it became clear that the forces of the Arab armies that came to Palestine on May 15, 1948 and were stationed in various parts of it were actually stationed and participating in the fighting only in the areas allocated to the Arab state according to the partition decision. Meanwhile, the Jewish forces did not commit to this, as they not only occupied the areas designated for the Jewish state, but also attacked and occupied areas designated for the Arab state even before the British forces left Palestine on May 15, 1948.",
        "The town of Tulkarm is a city in Palestine located in the middle of the coastal plain and is 55-125 meters above sea level. Its land area is 32,610 dunams. The city of Tulkarm is located in the eastern part of the coastal plain of Palestine, at the confluence of latitude 19.32 and longitude 35.1, and is about 15 km from the sea coast.  The Mediterranean, where the plain meets the feet of the mountains (Nablus Mountains). This location had commercial and military importance that had a major impact on the growth of the city, as it was a crossroads of trade routes and a corridor for military invasions between Egypt and the Levant.  This site feature has been given a distinctive defensive characteristic. It is also a center for land transportation between the coast and the interior and between the north and the south. It is easily accessible by a network of paved roads and the railway line passing through it. This site is also distinguished by the fertility of the soil and the abundance of water, whether rain or groundwater, and these conditions  It greatly helped the city's growth and development",
        'Nablus is a former Canaanite city and it is one of the oldest cities in the world. The city lies along a narrow and fertile valley running roughly East-West between two mountains, Ebal and Jerzim. The entire Nablus district has about 205,400 inhabitants. Nablus is known for its delicious Knafeh, olive oil, cheese and soap. Nablus is currently undergoing a face-lift with new infrastructure being built in New Nablus. The Nabulsi accent of the Palestinian dialect replace the letter "M" with "N" when used at the end of the word so the word "kifkom" is pronounced "kifkon" or "salamo 3alaykom" becomes "salamo 3alaykon" in Nabulsi Palestinian. Moreover, the Nabulsi dialect uses "e" instead of "a" at the end of a word, as an example the word "heyha" (here it is) become "heyhee" in Nabulsi. This is an aspect of the Nabulsi dialect that non-Nabulsi Palestinians often find funny.The Roman name of Nablus is Flavia Neapolis.',
        "Jaffa Known in Arabic as Yafa, in Hebrew as Yafo, and in ancient biblical writings as Joppa, Jaffa has been occupied for millennia and conquered by numerous invaders and empires, including Romans, crusaders, Ottomans, Napoleon, the Egyptian campaign of Ibrahim Pasha, the British, and finally, Israel. Along with ACRE, Jaffa was one of Palestine's main two seaports until the twentieth century. It was a trade city of major importance, as well as the traditional point of arrival for first pilgrims and later Jewish immigrants. Given the city's fertile and irrigated farmland and central location, agriculture and trade were the mainstays of Jaffa's economy. Jaffa was also noted for its large fruit groves, particularly its famous orange groves, home of the renowned Jaffa orange, which was exported throughout the world. Jaffa's position as Palestine's gateway to the world made it one of the country's most important centers of trade. Trade grew during the Egyptian period, and Jaffa's size and importance grew further as Palestine became increasingly linked with the industrial European economy in the nineteenth century .Importing and exporting were facilitated by the opening of a railroad line to Jerusalem in 1892. After World War I, the railroad line starting in Qantara was extended through Jaffa to Haifa. Jaffa was also a center for fishing and the manufacture of soap and olive oil, as well as benefiting from tourism and pilgrimage.",
        "The word Ramallah means “God wanted” or “God decreed.” This name was given to it after the Middle Ages, especially since Ramallah was a ruin within the lands of the village of Al-Bireh. Ramallah, as is the case with its sister Al-Bireh, was not mentioned in ancient history until the Roman era.  It seems that Ramallah during the period of the Arab-Islamic conquest was nothing more than a ruin, but it began to grow little by little after that. During the Crusades, Ramallah was a small Crusader agricultural colony that the Crusaders called Ramalie. The tower in the Tira area appears to be the remains of a Crusader building from this period. Popular history links the emergence of modern Ramallah with the migration of two Arab families, one Muslim and the other Christian, from Shobak in southern Jordan in the late fifteenth century AD. The Christian family is the Rashid Al-Haddadin family who resided in Ramallah, which was a ruin belonging to one of the Al-Bireh families, and the second is Muslim, the family of Hussein Tanash.  Who resided in Al-Bireh and integrated with her families",
        "Located in Palestine's coastal plain, Ramla differs from many Palestinian towns in its relatively recent origins. It was established by the Arabs in 716 C.E. and contains the tomb venerated by Muslims as that of the Qur'anic figure Salih. Ramla constituted a very important point along communications and transportation lines (including railroad) in Palestine. This fact has long placed it at the center of campaigns by various invaders throughout history, many of which-including those of the Crusaders and Napoleon Bonaparte have seized it from its Muslim defenders. Ramla was also a longtime administrative center in Palestine. It was the capital of the Jund Filastin during the early Islamic period, and the center of the subdistrict bearing its name during the PALESTINE MANDATE. The Mandate era witnessed a phenomenal growth in the town's population as well: from some 6,500 before the World War I to 16,380 by 1946.",
        "Jerusalem is considered a holy city for the three monotheistic religions: Judaism, Christianity, and Islam. Jerusalem has been a holy city for Jews since the tenth century BC. Jewish law says that their most important prayers should be directed toward Jerusalem. As for Christianity, it is the location of the Church of the Holy Sepulcher, as it is the city that witnessed the crucifixion of Christ.  And his resurrection, as for Muslims, it contains Al-Aqsa Mosque, the third holiest mosque for Muslims and the first of the two qiblahs before prayer towards the Kaaba. Also from Jerusalem, the Prophet Muhammad ascended to the seventh heaven according to Islamic belief.  This three-fold importance and sanctity has always made this city throughout history a center of great interest for all followers of the heavenly religions. It has always gathered followers of these religions under its shadow, and has always witnessed various wars to control it, which often took on a religious character.The most important Palestinian institution in Jerusalem was Dar Al-Sharq on Ubaida Street, but the Israeli police closed it in August 2001. The international community, including the United Nations, does not recognize Jerusalem as the capital of Israel as all foreign embassies were set up in other cities (especially in Tel Aviv  ).  The population of Jerusalem is 724,000 people (according to statistics of May 24, 2006(2)) within an area of ​​123 km2 (the area determined by the Israeli government in June 1967).",
        "The city of Hebron today, especially the Old City, is experiencing a tragic situation with the presence of the most ferocious racist settlers, the most extremist and politically and religiously fanatical, and even the most hateful and hateful of Arabs, as more than 68% of its population abandoned it as a result of the policy of humiliation, harassment, closure, checkpoints and massacres committed by the occupation army and its settlers, and it is known that  The Hebron Governorate has lost 51% of its lands since the beginning of the occupation in 1967 AD, as a result of its plundering for settlement and military purposes. Large areas of the governorate’s lands were annexed to the lands occupied in 1948. As for the annexation and apartheid wall, which passes through the governorate’s lands, which...  Its length is more than 186 km, and it devours more than 60% of the agricultural land area, 15% of the irrigated land, and an area of ​​565 thousand dunums of land in general, and it is included in the settlements, most of which have been expanded, and within  The Green Line also, and the wall uproots more than 250,000 olive seedlings, cuts off large areas of pastoral land, destroys the structure of agricultural production, both plant and animal, and controls water sources, as it constituted a fatal blow to the economy in the governorate. This wall will lead to the siege of about 40 people.  )) One thousand citizens, residing within the Old City of Hebron, and this constitutes a real disaster for the governorate’s population of six hundred thousand people. Let it be known that the apartheid wall and bypass roads will divide the governorate into 6)) areas cut off and isolated from each other, besieging the governorate and isolating it from the rest of the governorates.  Motherland.  Let it be known that the new changes in the course of the apartheid wall in the West Bank and the area of ​​isolated lands behind it have intensified in two areas. The first is located in the southeast of the West Bank in the southern Jordan Valley region, adjacent to the natural areas in the south of the West Bank, where an extension of the separation wall was approved from the south of Hebron Governorate towards  The north-east, as a result of which 53.5 kilometers were added to the length of the wall there, and as a result 153,780 thousand dunums were isolated between the extension of the new wall and the Green Line on the Dead Sea side.  Also, the new addition to the wall’s route led to the isolation of part of the Palestinian rights in the Dead Sea region, as an area of ​​71 kilometers (37%) was isolated out of a total of 194 kilometers, which is the total area allocated to the Palestinians there. It should be noted here that  The Israeli occupation army has cut off the Palestinians' access to the Dead Sea areas as of 2007.",
        "Inhabited since at least the 15th century BCE,Gaza has been dominated by different peoples and empires throughout its history. The Philistines made it a part of their pentapolis after the Ancient Egyptians had ruled it for nearly 350 years. Under the Roman Empire Gaza experienced relative peace and its port flourished. In 635 CE, it became the first city in Palestine to be conquered by the Muslim Rashidun army and quickly developed into a center of Islamic law. However, by the time the Crusaders invaded the country starting in 1099, Gaza was in ruins. In later centuries, Gaza experienced several hardships—from Mongol raids to floods and locusts, reducing it to a village by the 16th century, when it was incorporated into the Ottoman Empire. During the first half of Ottoman rule, the Ridwan dynasty controlled Gaza and under them the city went through an age of great commerce and peace. The municipality of Gaza was established in 1893. Gaza fell to British forces during World War I, becoming a part of Mandatory Palestine. As a result of the 1948 Arab–Israeli War, Egypt administered the newly formed Gaza Strip territory and several improvements were undertaken in the city. Gaza was occupied by Israel in the Six-Day War in 1967, and in 1993, the city was transferred to the newly created Palestinian National Authority. In the months following the 2006 election, an armed conflict broke out between the Palestinian political factions of Fatah and Hamas, resulting in the latter taking power in Gaza. The Gaza Strip was then subject to an Israeli-led, Egyptian-supported blockade.[6] Israel eased the blockade allowing consumer goods in June 2010, and Egypt reopened the Rafah Border Crossing in 2011 to pedestrians.",
        "Studying the lands of the Beersheba tribes before the Nakba and displacement is extremely important, because this research and study is a trust in our hands, we, the generation of this time. We must know every little thing about our lands in the Beersheba district, and also pass it on to the next generations of our children so that our issue is not shrouded in ignorance and forgetfulness, God forbid. Information about the lands of the Beersheba district must reach all the people of the Beersheba district honestly and transparently, and I will not hide from you that there are some difficulties in the field of this study because we derive most of our information from men and women who lived through the Nakba and displacement, and their ages must exceed 75 years. I mean that he was born in our occupied lands and was displaced from his lands, and he is conscious and aware of the places and their names. This is for a generation that is decreasing day after day due to the absence of death and their old age.... I rely on my studies and derive information from several sources Among them..."
    ];

    const imageLabels = [
        'Safad - صفد',
        'Acre -  عكا',
        'Tiberias -  طبريا',
        'Haifa - حيفا',
        'Nazareth  - الناصرة',
        'Baysan  - بيسان',
        'Jenin - جنين',
        'Tulkarm  -  طولكرم',
        'Nablus  -  نابلس',
        'Jaffa - يافا',
        'Ramallah  - رام الله',
        'Al Ramla  - الرملة',
        'Jerusalem - القدس',
        'Hebron -  الخليل',
        'Gaza -  غزة',
        'Beersheba - بئر سبع'
    ];

    imagePaths.forEach((path, index) => {
        const imgContainer = document.createElement('div');
        imgContainer.classList.add('image-container');

        const img = document.createElement('img');
        img.src = path;
        img.alt = `Image ${index + 1}`;
        img.addEventListener('click', () => openPopup(imageTexts[index]));

        const label = document.createElement('p');
        label.textContent = imageLabels[index];

        imgContainer.appendChild(img);
        imgContainer.appendChild(label);
        grid.appendChild(imgContainer);
    });
}


// Function to open the popup with text
function openPopup(text) {
    const popup = document.getElementById('popup');
    const popupText = document.getElementById('popup-text');
    popupText.textContent = text;
    popup.style.display = 'block';
}

// Function to close the popup
function closePopup() {
    const popup = document.getElementById('popup');
    popup.style.display = 'none';
}

// Call the function to create the image grid
createImageGrid();
